// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozqz2OXHSfkdnS54MB1PqA1jNxiFa7bM',
    appId: '1:907440202599:web:8c293f3225f656d952c5c2',
    messagingSenderId: '907440202599',
    projectId: 'nexus-application-43440',
    authDomain: 'nexus-application-43440.firebaseapp.com',
    storageBucket: 'nexus-application-43440.firebasestorage.app',
    measurementId: 'G-4VJXR36YMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKkIxhgcBK2m6jdUF4EjMDvrBN2uqZsgI',
    appId: '1:907440202599:android:331148670ef3351852c5c2',
    messagingSenderId: '907440202599',
    projectId: 'nexus-application-43440',
    storageBucket: 'nexus-application-43440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw9yj0p74mivvGjymBleQKfWBnRw9AV9A',
    appId: '1:907440202599:ios:90c1b56ddfb1f9c252c5c2',
    messagingSenderId: '907440202599',
    projectId: 'nexus-application-43440',
    storageBucket: 'nexus-application-43440.firebasestorage.app',
    androidClientId: '907440202599-hk3clcelaf6s4kl6c7jtp5ou1areri7b.apps.googleusercontent.com',
    iosClientId: '907440202599-io5qtnu9kg6l9o0gps24gnit4qc2vn24.apps.googleusercontent.com',
    iosBundleId: 'com.example.newNexusApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw9yj0p74mivvGjymBleQKfWBnRw9AV9A',
    appId: '1:907440202599:ios:90c1b56ddfb1f9c252c5c2',
    messagingSenderId: '907440202599',
    projectId: 'nexus-application-43440',
    storageBucket: 'nexus-application-43440.firebasestorage.app',
    androidClientId: '907440202599-hk3clcelaf6s4kl6c7jtp5ou1areri7b.apps.googleusercontent.com',
    iosClientId: '907440202599-io5qtnu9kg6l9o0gps24gnit4qc2vn24.apps.googleusercontent.com',
    iosBundleId: 'com.example.newNexusApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAozqz2OXHSfkdnS54MB1PqA1jNxiFa7bM',
    appId: '1:907440202599:web:42aea606b63f169f52c5c2',
    messagingSenderId: '907440202599',
    projectId: 'nexus-application-43440',
    authDomain: 'nexus-application-43440.firebaseapp.com',
    storageBucket: 'nexus-application-43440.firebasestorage.app',
    measurementId: 'G-QH0F30K6NC',
  );
}
